package agentplatform

import (
	"bytes"
	"errors"
	"flag"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"

	"github.com/giantswarm/giantswarm-platform-manager/definitions"
)

var update = flag.Bool("update", false, "rewrite the golden filesets from the current render")

// The installation shapes with a golden fileset under testdata/<shape>/.
const (
	shapePublicCustomer         = "public-customer"
	shapeGiantswarmOwned        = "giantswarm-owned"
	shapeHubPrivateTarget       = "hub-private-target"
	shapeMultiClusterAggregator = "multi-cluster-aggregator"
)

// shapes are the installation shapes, in the order the goldens are rendered.
var shapes = []string{shapePublicCustomer, shapeGiantswarmOwned, shapeHubPrivateTarget, shapeMultiClusterAggregator}

func loadInput(t *testing.T, shape string) (map[string]any, map[string]string) {
	t.Helper()
	raw, err := fs.ReadFile(os.DirFS(filepath.Join("testdata", shape)), "input.yaml")
	if err != nil {
		t.Fatal(err)
	}
	var doc struct {
		Input   map[string]any    `yaml:"input"`
		Secrets map[string]string `yaml:"secrets"`
	}
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		t.Fatal(err)
	}
	return doc.Input, doc.Secrets
}

func TestGolden(t *testing.T) {
	for _, shape := range shapes {
		t.Run(shape, func(t *testing.T) {
			input, secrets := loadInput(t, shape)
			result, err := Render(input, secrets)
			if err != nil {
				t.Fatal(err)
			}
			got := result.Tree()
			dir := filepath.Join("testdata", shape, "golden")
			if *update {
				if err := os.RemoveAll(dir); err != nil {
					t.Fatal(err)
				}
				for name, content := range got {
					if err := os.MkdirAll(filepath.Dir(filepath.Join(dir, name)), 0o750); err != nil {
						t.Fatal(err)
					}
					if err := os.WriteFile(filepath.Join(dir, name), content, 0o600); err != nil {
						t.Fatal(err)
					}
				}
			}
			want := map[string][]byte{}
			golden := os.DirFS(dir)
			err = fs.WalkDir(golden, ".", func(path string, d fs.DirEntry, err error) error {
				if err != nil || d.IsDir() {
					return err
				}
				content, err := fs.ReadFile(golden, path)
				if err != nil {
					return err
				}
				want[filepath.FromSlash(path)] = content
				return nil
			})
			if err != nil {
				t.Fatal(err)
			}
			for name, content := range want {
				if !bytes.Equal(got[name], content) {
					t.Errorf("%s differs from the golden (run with -update to accept):\n--- want\n%s\n--- got\n%s", name, content, got[name])
				}
			}
			for name := range got {
				if _, ok := want[name]; !ok {
					t.Errorf("%s rendered but not in the golden (run with -update to accept)", name)
				}
			}
		})
	}
}

func TestSecretFilesCarryNoValues(t *testing.T) {
	for _, shape := range shapes {
		input, secrets := loadInput(t, shape)
		result, err := Render(input, secrets)
		if err != nil {
			t.Fatal(err)
		}
		for repo, files := range result.Files {
			for path, f := range files {
				if !strings.Contains(path, "secret") && !strings.Contains(path, "credential") {
					if len(f.Generated) > 0 {
						t.Errorf("%s: %s carries generated placeholders but is not named as a secret file", repo, path)
					}
					continue
				}
				if !bytes.Contains(f.Content, []byte("kind: Secret")) {
					continue
				}
				for _, g := range f.Generated {
					if !bytes.Contains(f.Content, []byte(g.Placeholder)) {
						t.Errorf("%s: %s lists %s but does not carry its placeholder", repo, path, g.Name)
					}
				}
			}
		}
	}
}

// Two installations of one organisation land in the same repositories, a wave
// commits them into one pull request per repository, and the commit step draws
// one value per generated name across a pull request: every generated name
// carries its installation and no name is generated by two installations, so
// no client secret is ever shared between installations or organisations. The
// one name two renders share is a hub's client in a target's Dex — one client,
// its secret in the hub's credentials and the target's Dex, named after both.
func TestGeneratedValuesArePerInstallation(t *testing.T) {
	generatedBy := map[string]string{}
	for _, shape := range []string{shapePublicCustomer, shapeMultiClusterAggregator} {
		input, secrets := loadInput(t, shape)
		result, err := Render(input, secrets)
		if err != nil {
			t.Fatal(err)
		}
		name, _ := input["installation"].(map[string]any)["name"].(string)
		for repo, files := range result.Files {
			for path, f := range files {
				for _, g := range f.Generated {
					if !strings.Contains("-"+g.Name+"-", "-"+name+"-") {
						t.Errorf("%s: %s: %s does not carry the installation %s", repo, path, g.Name, name)
					}
					other, seen := generatedBy[g.Name]
					if seen && other != name && g.Name != exchangeSecretName(other, name) && g.Name != exchangeSecretName(name, other) {
						t.Errorf("%s is generated by %s and %s: one value would serve two installations", g.Name, other, name)
					}
					generatedBy[g.Name] = name
				}
			}
		}
	}
}

func TestOwnedPathsOnly(t *testing.T) {
	for _, shape := range shapes {
		t.Run(shape, func(t *testing.T) { testOwnedPathsOnly(t, shape) })
	}
}

func testOwnedPathsOnly(t *testing.T, shape string) {
	input, secrets := loadInput(t, shape)
	result, err := Render(input, secrets)
	if err != nil {
		t.Fatal(err)
	}
	in, err := Parse(input)
	if err != nil {
		t.Fatal(err)
	}
	name := in.Installation.Name
	// The platform's portal section lives in the organisation's own portal, which
	// another installation of the organisation may host.
	portal := "management-clusters/" + in.portalHost() + "/extras/backstage/" + portalDir + "/"
	for repo, files := range result.Files {
		for path := range files {
			if !strings.Contains(path, "/"+name+"/") && !strings.HasPrefix(path, portal) {
				t.Errorf("%s: %s is outside the installation's own directories", repo, path)
			}
			for _, inc := range result.Includes {
				if inc.Repository == repo && inc.Path == path {
					t.Errorf("%s: %s is rendered and also an include of a shared file", repo, path)
				}
			}
		}
	}
	// Enable then disable: the disabled fileset is empty by construction, so the
	// delta is exactly the rendered paths, and every one of them may be deleted.
	if result.Len() == 0 {
		t.Fatal("an enabled installation renders no files")
	}
}

// TestProbesAreLiveDimensions holds the probes to features.yaml: every probe
// observes a kind: live dimension of the feature it names, every action names
// a feature, and every live dimension has at least one probe on the
// public-customer shape.
func TestProbesAreLiveDimensions(t *testing.T) {
	raw, err := definitions.FS.ReadFile("agent-platform/features.yaml")
	if err != nil {
		t.Fatal(err)
	}
	var doc struct {
		Features map[string]struct {
			Dimensions []struct {
				ID   string `yaml:"id"`
				Kind string `yaml:"kind"`
			} `yaml:"dimensions"`
		} `yaml:"features"`
	}
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		t.Fatal(err)
	}
	live := map[string]string{} // dimension id -> feature
	for feature, f := range doc.Features {
		for _, d := range f.Dimensions {
			if d.Kind == "live" {
				live[d.ID] = feature
			}
		}
	}
	if len(live) == 0 {
		t.Fatal("features.yaml has no live dimension")
	}
	probed := map[string]bool{}
	for _, shape := range shapes {
		input, secrets := loadInput(t, shape)
		result, err := Render(input, secrets)
		if err != nil {
			t.Fatal(err)
		}
		if len(result.Probes) == 0 {
			t.Errorf("%s: no probes", shape)
		}
		for _, p := range result.Probes {
			feature, ok := live[p.ID]
			if !ok {
				t.Errorf("%s: probe %s is not a live dimension of features.yaml", shape, p.ID)
				continue
			}
			if feature != p.Feature {
				t.Errorf("%s: probe %s names feature %s, features.yaml has it under %s", shape, p.ID, p.Feature, feature)
			}
			if shape == shapePublicCustomer {
				probed[p.ID] = true
			}
		}
		for _, a := range result.Actions {
			if _, ok := doc.Features[a.Feature]; !ok {
				t.Errorf("%s: action %s names feature %s, which features.yaml does not have", shape, a.ID, a.Feature)
			}
		}
	}
	ids := make([]string, 0, len(live))
	for id := range live {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	for _, id := range ids {
		if !probed[id] {
			t.Errorf("live dimension %s of feature %s has no probe on the public-customer shape", id, live[id])
		}
	}
}

func TestRefusals(t *testing.T) {
	base, secrets := loadInput(t, shapePublicCustomer)
	owned, _ := loadInput(t, shapeGiantswarmOwned)
	target := func(private bool) map[string]any {
		return map[string]any{"installation": "x", "baseDomain": "x.example", "private": private}
	}
	clone := func(mutate func(map[string]any)) map[string]any {
		var c map[string]any
		b, _ := yaml.Marshal(base)
		_ = yaml.Unmarshal(b, &c)
		mutate(c)
		return c
	}
	federation := func(m map[string]any) map[string]any {
		return m["installation"].(map[string]any)["federation"].(map[string]any)
	}
	cases := []struct {
		name    string
		input   map[string]any
		secrets map[string]string
		err     error
		names   string
	}{
		{"unknown top-level key", clone(func(m map[string]any) { m["colourScheme"] = "dark" }), secrets, ErrInput, "colourScheme"},
		{"a former input is unknown", clone(func(m map[string]any) { m["kagent"] = map[string]any{"enabled": true} }), secrets, ErrInput, "kagent"},
		{"unknown record key", clone(func(m map[string]any) { m["installation"].(map[string]any)["replicas"] = 3 }), secrets, ErrInput, "replicas"},
		{"empty model key", owned, nil, ErrEmptySecret, fieldModelKey},
		{"unknown secret value", base, map[string]string{fieldModelKey: "x"}, ErrUnknownSecret, fieldModelKey},
		{"serving on the 3 line", clone(func(m map[string]any) { m["modelServing"] = map[string]any{"enabled": true} }), secrets, ErrInput, "modelServing.enabled"},
		{"targets without a broker client", clone(func(m map[string]any) {
			federation(m)["targets"] = []any{target(false)}
		}), secrets, ErrInput, "federation.brokerClientId"},
		{"private target without the tunnel", clone(func(m map[string]any) {
			f := federation(m)
			f["brokerClientId"], f["targets"] = "b", []any{target(true)}
		}), secrets, ErrInput, "federation.tunnel"},
		{"tunnel without a private target", clone(func(m map[string]any) {
			f := federation(m)
			f["brokerClientId"], f["targets"] = "b", []any{target(false)}
			f["tunnel"] = map[string]any{"jwks": "{}", "trustBundleProvisioned": true}
		}), secrets, ErrInput, "federation.tunnel"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			_, err := Render(c.input, c.secrets)
			if !errors.Is(err, c.err) {
				t.Fatalf("got %v, want %v", err, c.err)
			}
			if !strings.Contains(err.Error(), c.names) {
				t.Fatalf("%q does not name %q", err, c.names)
			}
		})
	}
}
